package MenuMedico;

import EmpregadosClinica.Medico;
import Fichas.Prontuario;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;


public class TelaMedAtualizarProntuario extends javax.swing.JFrame {
    EntityManager em;
    Medico medicoLogado;
    Prontuario prontuario;

    public TelaMedAtualizarProntuario(Medico medicoLogado, Prontuario prontuario, EntityManager em) {
        initComponents();
        this.medicoLogado = medicoLogado;
        this.em = em;
        this.prontuario = prontuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoAtualizarDiag = new javax.swing.JButton();
        botaoAtualizarTratamento = new javax.swing.JButton();
        botaoAtualizarSint = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualização de Prontuário");

        botaoAtualizarDiag.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botaoAtualizarDiag.setText("Atualizar Diagnóstico");
        botaoAtualizarDiag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarDiagActionPerformed(evt);
            }
        });

        botaoAtualizarTratamento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botaoAtualizarTratamento.setText("Atualizar Tratamento");
        botaoAtualizarTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarTratamentoActionPerformed(evt);
            }
        });

        botaoAtualizarSint.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botaoAtualizarSint.setText("Atualizar Sintomas");
        botaoAtualizarSint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarSintActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sobre");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoAtualizarTratamento)
                        .addComponent(botaoAtualizarDiag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAtualizarSint, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(botaoAtualizarSint)
                .addGap(50, 50, 50)
                .addComponent(botaoAtualizarDiag)
                .addGap(50, 50, 50)
                .addComponent(botaoAtualizarTratamento)
                .addGap(50, 50, 50)
                .addComponent(botaoVoltar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        TelaMedGerenciarProntuarios telaAnterior = new TelaMedGerenciarProntuarios(medicoLogado, em);
        telaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoAtualizarSintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarSintActionPerformed
        String sintomas = JOptionPane.showInputDialog(null, "Insira os sintomas: (os antigos serão substituidos)");
        medicoLogado.atualizarSintomasProntuario(prontuario, sintomas);
        JOptionPane.showMessageDialog(null,"Sintomas atualizados com sucesso");
    }//GEN-LAST:event_botaoAtualizarSintActionPerformed

    private void botaoAtualizarDiagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarDiagActionPerformed
        String diagnostico = JOptionPane.showInputDialog(null, "Insira o diagnostico: (o antigo será substituido)");
        medicoLogado.atualizarDiagnosticoProntuario(prontuario, diagnostico);
        JOptionPane.showMessageDialog(null,"Diagnostico atualizado com sucesso");
    }//GEN-LAST:event_botaoAtualizarDiagActionPerformed

    private void botaoAtualizarTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarTratamentoActionPerformed
        String tratamento = JOptionPane.showInputDialog(null, "Insira o tratamento: (o antigo será substituido)");
        medicoLogado.atualizarTratamentoProntuario(prontuario, tratamento);
        JOptionPane.showMessageDialog(null,"Tratamento atualizado com sucesso");
    }//GEN-LAST:event_botaoAtualizarTratamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizarDiag;
    private javax.swing.JButton botaoAtualizarSint;
    private javax.swing.JButton botaoAtualizarTratamento;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
