package MenuMedico;

import EmpregadosClinica.Medico;
import Sistema.PacienteCadastrado;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

public class TelaMedInfoAdicionalAtualizar extends javax.swing.JFrame {
    private Medico medicoLogado;
    private PacienteCadastrado paciente;
    private EntityManager em;

    public TelaMedInfoAdicionalAtualizar(EntityManager em, Medico medicoLogado, PacienteCadastrado paciente) {
        initComponents();
        this.em = em;
        this.medicoLogado = medicoLogado;
        this.paciente = paciente;
        mostrarInfos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkboxFuma = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        checkboxBebe = new javax.swing.JCheckBox();
        checkboxDiabete = new javax.swing.JCheckBox();
        checkboxColesterol = new javax.swing.JCheckBox();
        checkboxDoencaCardio = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoAtualizar = new javax.swing.JButton();
        textCirurgias = new javax.swing.JTextField();
        textAlergias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização de Informações Adicionais");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setToolTipText("");

        checkboxFuma.setText("Fuma");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Informações adicionais");

        checkboxBebe.setText("Bebe");

        checkboxDiabete.setText("Possui diabetes");

        checkboxColesterol.setText("Possui colesterol alto");

        checkboxDoencaCardio.setText("Possui alguma doença cardiaca");

        jLabel2.setText("Cirurgias feitas:");

        jLabel3.setText("Alergias:");

        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(botaoAtualizar)
                .addGap(243, 243, 243))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCirurgias)
                    .addComponent(textAlergias)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkboxFuma)
                            .addComponent(jLabel1)
                            .addComponent(checkboxBebe)
                            .addComponent(checkboxDiabete)
                            .addComponent(checkboxColesterol)
                            .addComponent(checkboxDoencaCardio)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(checkboxFuma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkboxBebe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkboxDiabete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkboxColesterol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkboxDoencaCardio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoAtualizar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void mostrarInfos(){
        // Obtém as informações do paciente e as exibe nos campos
        checkboxDiabete.setSelected(paciente.isDiabete());
        checkboxFuma.setSelected(paciente.isFuma());
        checkboxBebe.setSelected(paciente.isBebe());
        checkboxColesterol.setSelected(paciente.isColesterolAlto());
        checkboxDoencaCardio.setSelected(paciente.isDoencaCardiaca());
        textCirurgias.setText((paciente.getCirurgias()).toString());
        textAlergias.setText((paciente.getAlergias()).toString());
    }
    
    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        // Obtém as informações nos campos e chama os métodos de atualização da Classe Médico
        boolean diabete = checkboxDiabete.isSelected();
        boolean fuma = checkboxFuma.isSelected();
        boolean bebe = checkboxBebe.isSelected();
        boolean doenca = checkboxDoencaCardio.isSelected();
        boolean colesterol = checkboxColesterol.isSelected();
        String cirurgias = textCirurgias.getText();
        String alergias = textAlergias.getText();
        medicoLogado.atualizarPacienteDiabete(diabete, paciente);
        medicoLogado.atualizarPacienteFuma(fuma, paciente);
        medicoLogado.atualizarPacienteBebe(bebe,paciente);
        medicoLogado.atualizarPacienteAlergias(alergias, paciente);
        medicoLogado.atualizarPacienteCirurgias(cirurgias, paciente);
        medicoLogado.atualizarPacienteColesterol(colesterol, paciente);
        medicoLogado.atualizarPacienteDoencaCardiaca(doenca, paciente);
        JOptionPane.showMessageDialog(null,"Paciente atualizado com sucesso!");
        this.dispose();
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JCheckBox checkboxBebe;
    private javax.swing.JCheckBox checkboxColesterol;
    private javax.swing.JCheckBox checkboxDiabete;
    private javax.swing.JCheckBox checkboxDoencaCardio;
    private javax.swing.JCheckBox checkboxFuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textAlergias;
    private javax.swing.JTextField textCirurgias;
    // End of variables declaration//GEN-END:variables
}
