package MenuSecretaria;

import Atendimento.Consulta;
import EmpregadosClinica.Secretaria;
import Sistema.MedicoCadastrado;
import Sistema.PacienteCadastrado;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

public class TelaSecMarcarConsulta extends javax.swing.JFrame {
    EntityManager em;
    Secretaria secretariaLogada;
    /**
     * Creates new form TelaSecMarcarConsulta
     */
    public TelaSecMarcarConsulta(Secretaria secretariaLogada, EntityManager em) {
        initComponents();
        this.secretariaLogada = secretariaLogada;
        this.em = em;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoDeConsulta = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cpfPacienteConsulta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        crmConsulta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dataConsulta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        horarioConsulta = new javax.swing.JTextField();
        consultaNormal = new javax.swing.JRadioButton();
        consultaRetorno = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        botaoMarcar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CPF do paciente: (apenas números)");

        jLabel2.setText("CRM do médico que atenderá o paciente");

        jLabel3.setText("Data: (dd/mm/aaaa)");

        jLabel4.setText("Horário: (hh:mm)");

        grupoTipoDeConsulta.add(consultaNormal);
        consultaNormal.setText("Normal");

        grupoTipoDeConsulta.add(consultaRetorno);
        consultaRetorno.setText("Retorno");

        jLabel5.setText("Tipo da consulta:");

        botaoMarcar.setText("Marcar");
        botaoMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMarcarActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfPacienteConsulta)
                            .addComponent(crmConsulta)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(horarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel4)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(consultaNormal)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(consultaRetorno)))))
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoMarcar)
                        .addGap(196, 196, 196))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfPacienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crmConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaNormal)
                    .addComponent(consultaRetorno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoMarcar)
                    .addComponent(botaoSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMarcarActionPerformed
        String cpfPaciente = cpfPacienteConsulta.getText();
        
        String crmMedico = crmConsulta.getText();
        
        String data = dataConsulta.getText();
        String horario = horarioConsulta.getText();
        
        String tipoConsulta = "";
        if(consultaNormal.isSelected()){
            tipoConsulta = "Normal";
        }
        if(consultaRetorno.isSelected()){
            tipoConsulta = "Retorno";
        }
        
        if(cpfPaciente != "" && crmMedico != "" && data != "" && horario != "" && tipoConsulta != "") {
            MedicoCadastrado medicoCred = em.find(MedicoCadastrado.class, crmMedico);
            PacienteCadastrado pacienteCred = em.find(PacienteCadastrado.class, cpfPaciente);
            if(medicoCred != null && pacienteCred != null) {
                // criacao do id da consulta
                StringBuilder idConsulta = new StringBuilder();
                idConsulta.append(data);
                String resIdConsulta = idConsulta.toString().replaceAll("[/]", "");
                idConsulta = new StringBuilder(resIdConsulta);

                idConsulta.append("/");
                idConsulta.append(horario);
                resIdConsulta = idConsulta.toString().replaceAll("[:]", "");
                idConsulta = new StringBuilder(resIdConsulta);

                idConsulta.append("/");
                idConsulta.append(crmMedico);
                idConsulta = new StringBuilder(resIdConsulta);

                resIdConsulta = idConsulta.toString();

                // Marcando consulta
                secretariaLogada.marcarConsulta(data, horario, medicoCred, pacienteCred, tipoConsulta, resIdConsulta);
                JOptionPane.showMessageDialog(null,"Consulta marcada com Sucesso");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Paciente/Medico não encontrado", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.", "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_botaoMarcarActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMarcar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JRadioButton consultaNormal;
    private javax.swing.JRadioButton consultaRetorno;
    private javax.swing.JTextField cpfPacienteConsulta;
    private javax.swing.JTextField crmConsulta;
    private javax.swing.JTextField dataConsulta;
    private javax.swing.ButtonGroup grupoTipoDeConsulta;
    private javax.swing.JTextField horarioConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
