package MenuSecretaria;

import Atendimento.Consulta;
import EmpregadosClinica.Secretaria;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.DefaultListModel;


public class TelaSecRelatorio extends javax.swing.JFrame {
    EntityManager em;
    Secretaria secretariaLogada;
    List<List<Consulta>> consultasAmanha;

    public TelaSecRelatorio(Secretaria secretariaLogada, List<List<Consulta>> consultasAmanha, EntityManager em){
        initComponents();
        this.em = em;
        this.secretariaLogada = secretariaLogada;
        this.consultasAmanha = consultasAmanha;
        preencherListaSemContato(consultasAmanha.get(0));
        preencherListaComContato(consultasAmanha.get(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaComContato = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaSemContato = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(ListaComContato);

        jScrollPane3.setViewportView(ListaSemContato);

        jLabel1.setText("Sem contato:");

        jLabel2.setText("Com contato:");

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(botaoFechar)
                .addGap(196, 196, 196))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoFechar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    
    public void preencherListaSemContato(List<Consulta> consultasAmanha) {
        List<String> model = new ArrayList<>();
        for (Consulta consulta : consultasAmanha) {
            model.add("Nome: " + consulta.getPaciente().getNome());    
        }
        ListaSemContato.setListData(model.toArray(new String[model.size()]));
    }
    
    public void preencherListaComContato(List<Consulta> consultasAmanha) {
        List<String> model = new ArrayList<>();
        for (Consulta consulta : consultasAmanha) {
            model.add("Nome:" + consulta.getPaciente().getNome() +", Email: " + consulta.getPaciente().getEmail() + ", Telefone: " + consulta.getPaciente().getTelefone());
        }
        ListaComContato.setListData(model.toArray(new String[model.size()]));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaComContato;
    private javax.swing.JList<String> ListaSemContato;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
