/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaSecAtualizarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaMedAtualizarPaciente
     */
    public TelaSecAtualizarPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NomeAtualizado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EndereçoAtualizado = new javax.swing.JButton();
        emailAtualizado = new javax.swing.JButton();
        telefoneAtualizado = new javax.swing.JButton();
        dataAtualizado = new javax.swing.JButton();
        convenioAtualizado = new javax.swing.JButton();
        BotaoVoltar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeAtualizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NomeAtualizado.setText("Nome");
        NomeAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAtualizadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("O que deseja atualizar?");

        EndereçoAtualizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EndereçoAtualizado.setText("Endereço");
        EndereçoAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndereçoAtualizadoActionPerformed(evt);
            }
        });

        emailAtualizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailAtualizado.setText("E-mail");
        emailAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAtualizadoActionPerformed(evt);
            }
        });

        telefoneAtualizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        telefoneAtualizado.setText("Telefone");
        telefoneAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneAtualizadoActionPerformed(evt);
            }
        });

        dataAtualizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dataAtualizado.setText("Data de Nascimento");
        dataAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAtualizadoActionPerformed(evt);
            }
        });

        convenioAtualizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        convenioAtualizado.setText("Convênio");
        convenioAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convenioAtualizadoActionPerformed(evt);
            }
        });

        BotaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(174, 174, 174))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataAtualizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefoneAtualizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailAtualizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EndereçoAtualizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeAtualizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convenioAtualizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(NomeAtualizado)
                .addGap(18, 18, 18)
                .addComponent(EndereçoAtualizado)
                .addGap(18, 18, 18)
                .addComponent(emailAtualizado)
                .addGap(18, 18, 18)
                .addComponent(telefoneAtualizado)
                .addGap(18, 18, 18)
                .addComponent(dataAtualizado)
                .addGap(18, 18, 18)
                .addComponent(convenioAtualizado)
                .addGap(18, 18, 18)
                .addComponent(BotaoVoltar)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sobre");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void NomeAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAtualizadoActionPerformed
        String nomeAtualizado = JOptionPane.showInputDialog(null, "Insira o novo nome do paciente:");
        JOptionPane.showMessageDialog(null,"Nome Atualizado!");
    }//GEN-LAST:event_NomeAtualizadoActionPerformed

    private void EndereçoAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndereçoAtualizadoActionPerformed
        String enderecoAtualizado = JOptionPane.showInputDialog(null, "Insira o novo endereço do paciente:");
        JOptionPane.showMessageDialog(null,"Endereço Atualizado!");
    }//GEN-LAST:event_EndereçoAtualizadoActionPerformed

    private void emailAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAtualizadoActionPerformed
        String emailAtualizado = JOptionPane.showInputDialog(null, "Insira o novo e-mail do paciente:");
        JOptionPane.showMessageDialog(null,"E-mail Atualizado!");
    }//GEN-LAST:event_emailAtualizadoActionPerformed

    private void telefoneAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneAtualizadoActionPerformed
        String telefoneAtualizado = JOptionPane.showInputDialog(null, "Insira o novo telefone do paciente:");
        JOptionPane.showMessageDialog(null,"Telefone Atualizado!");
    }//GEN-LAST:event_telefoneAtualizadoActionPerformed

    private void dataAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAtualizadoActionPerformed
        String dataAtualizada = JOptionPane.showInputDialog(null, "Insira o nova data de nascimento do paciente:");
        JOptionPane.showMessageDialog(null,"Data de nascimento Atualizada!");
    }//GEN-LAST:event_dataAtualizadoActionPerformed

    private void convenioAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convenioAtualizadoActionPerformed
        String convenioAtualizado = JOptionPane.showInputDialog(null, "Insira o novo convênio do paciente:");
        JOptionPane.showMessageDialog(null,"Convênio Atualizado!");
    }//GEN-LAST:event_convenioAtualizadoActionPerformed

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        TelaSecGerenciarPaciente telaAnterior = new TelaSecGerenciarPaciente();
        telaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecAtualizarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecAtualizarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecAtualizarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecAtualizarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSecAtualizarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JButton EndereçoAtualizado;
    private javax.swing.JButton NomeAtualizado;
    private javax.swing.JButton convenioAtualizado;
    private javax.swing.JButton dataAtualizado;
    private javax.swing.JButton emailAtualizado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton telefoneAtualizado;
    // End of variables declaration//GEN-END:variables
}
