/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Atendimento.Paciente;
import EmpregadosClinica.Secretaria;
import Sistema.PacienteCadastrado;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaSecGerenciarPaciente extends javax.swing.JFrame {
    EntityManager em;
    Secretaria secretariaLogada;
    /**
     * Creates new form TelaMedicoGerenciarPaciente
     */
    public TelaSecGerenciarPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        BotaoCadastrarPaciente = new javax.swing.JButton();
        BotaoRemoverPaciente = new javax.swing.JButton();
        BotaoAtualizarPaciente = new javax.swing.JButton();
        BotaoVoltar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jButton1.setText("Cadastrar Paciente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        BotaoCadastrarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotaoCadastrarPaciente.setText("Cadastrar Paciente");
        BotaoCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarPacienteActionPerformed(evt);
            }
        });

        BotaoRemoverPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotaoRemoverPaciente.setText("Remover Paciente");
        BotaoRemoverPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverPacienteActionPerformed(evt);
            }
        });

        BotaoAtualizarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotaoAtualizarPaciente.setText("Atualizar Paciente");
        BotaoAtualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarPacienteActionPerformed(evt);
            }
        });

        BotaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setText("Gerenciador de Pacientes");

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sobre");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotaoCadastrarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoAtualizarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoRemoverPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(64, 64, 64)
                .addComponent(BotaoCadastrarPaciente)
                .addGap(47, 47, 47)
                .addComponent(BotaoRemoverPaciente)
                .addGap(43, 43, 43)
                .addComponent(BotaoAtualizarPaciente)
                .addGap(45, 45, 45)
                .addComponent(BotaoVoltar)
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        TelaPrincipalSecretaria TelaAnterior = new TelaPrincipalSecretaria(secretariaLogada, em);
        TelaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed
    
    private void BotaoCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarPacienteActionPerformed
        TelaSecCadastrarPaciente TelaCadastro = new TelaSecCadastrarPaciente(secretariaLogada, em);
        TelaCadastro.setVisible(true);
    }//GEN-LAST:event_BotaoCadastrarPacienteActionPerformed

    private void BotaoRemoverPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverPacienteActionPerformed
        String cpf = JOptionPane.showInputDialog(null, "Insira o CPF do paciente que deseja atualizar", "CPF:", JOptionPane.QUESTION_MESSAGE);
        secretariaLogada.removerPaciente(em,cpf);
        JOptionPane.showMessageDialog(null,"Paciente Removido com Sucesso");
    }//GEN-LAST:event_BotaoRemoverPacienteActionPerformed

    private void BotaoAtualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarPacienteActionPerformed
        String cpf = JOptionPane.showInputDialog(null, "Insira o CPF do paciente que deseja atualizar", "CPF:", JOptionPane.QUESTION_MESSAGE);
        PacienteCadastrado pacienteCred = em.find(PacienteCadastrado.class, cpf);
        if(pacienteCred != null) {
            TelaSecAtualizarPaciente TelaAtualizacao = new TelaSecAtualizarPaciente(em, secretariaLogada, pacienteCred);
            TelaAtualizacao.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "CPF incorreto/Paciente não existe.", "Credenciais não encontradas", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoAtualizarPacienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAtualizarPaciente;
    private javax.swing.JButton BotaoCadastrarPaciente;
    private javax.swing.JButton BotaoRemoverPaciente;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
